# Generated by Django 5.1.3 on 2024-12-05 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role_name', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=150)),
                ('Status', models.CharField(max_length=15)),
                ('Assigned_permission', models.ManyToManyField(to='admin_dashboard.permission')),
            ],
        ),
        migrations.DeleteModel(
            name='user_table',
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='Roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard.role'),
        ),
    ]
