# Generated by Django 5.1.3 on 2024-12-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_permission_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('Status', models.CharField(default='active', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='Assigned_permission',
            field=models.ManyToManyField(to='admin_dashboard.permission1'),
        ),
    ]
