# Generated by Django 5.1.3 on 2024-12-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_permission1_alter_role_assigned_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
